version: 2

updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "@ahoo-wang/godex-*"
    groups:
      dev-dependencies:
        patterns:
          - "@biomejs/*"
          - "@types/*"
          - "typescript"
      fetcher-ecosystem:
        patterns:
          - "@ahoo-wang/fetcher*"
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: ci
      include: scope
