changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - question
      - wontfix
  categories:
    - title: 🚀 Features
      labels:
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 🔒 Security
      labels:
        - security
    - title: 📦 Dependencies
      labels:
        - dependencies
    - title: 🛠 Maintenance
      labels:
        - chore
        - maintenance
    - title: 📚 Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
