import {
	type BaseURLCapable,
	Fetcher,
	type TimeoutCapable,
} from "@ahoo-wang/fetcher";
import {
	type ApiMetadata,
	type ApiMetadataCapable,
	api,
	autoGeneratedError,
	body,
	post,
} from "@ahoo-wang/fetcher-decorator";
import type { JsonServerSentEventStream } from "@ahoo-wang/fetcher-eventstream";
import { JsonStreamResultExtractor } from "./stream-result-extractor.ts";

export interface ChatApiOptions extends BaseURLCapable, TimeoutCapable {
	apiKey: string;
}

const CHAT_COMPLETION_ENDPOINT = "chat/completions";

@api()
export class ChatApi<TReq, TRes, TChunk> implements ApiMetadataCapable {
	constructor(public readonly apiMetadata?: ApiMetadata) {}

	@post(CHAT_COMPLETION_ENDPOINT)
	chatCompletions(@body() request: TReq): Promise<TRes> {
		throw autoGeneratedError(request);
	}

	@post(CHAT_COMPLETION_ENDPOINT, {
		resultExtractor: JsonStreamResultExtractor,
	})
	streamChatCompletions(
		@body() request: TReq,
	): Promise<JsonServerSentEventStream<TChunk>> {
		throw autoGeneratedError(request);
	}
}

export function chatApi<TReq, TRes, TChunk>(
	options: ChatApiOptions,
): ChatApi<TReq, TRes, TChunk> {
	const fetcher = new Fetcher({
		baseURL: options.baseURL,
		timeout: options.timeout,
		headers: {
			Authorization: `Bearer ${options.apiKey}`,
		},
	});
	return new ChatApi({ fetcher: fetcher });
}
