import type {
	Metadata,
	PromptCacheRetention,
	ReasoningEffort,
	ReasoningSummary,
	ResponseError,
	ResponseFormatTextConfig,
	ServiceTier,
	TruncationStrategy,
	Verbosity,
} from "../shared";
import type { ResponseInputContent } from "./content";
import type { ResponseItem } from "./items";
import type { SummaryTextContent } from "./reasoning";
import type { ResponseIncludable } from "./request";
import type { ResponseTool, ResponseToolChoice } from "./tools";

export interface ResponseIncompleteDetails {
	reason?: "max_output_tokens" | "content_filter";
}

export type ResponseStatus =
	| "completed"
	| "failed"
	| "in_progress"
	| "cancelled"
	| "queued"
	| "incomplete";

export interface ResponseInputTokensDetails {
	cached_tokens?: number;
}

export interface ResponseOutputTokensDetails {
	reasoning_tokens?: number;
}

export interface ResponseUsage {
	input_tokens: number;
	output_tokens: number;
	total_tokens: number;
	input_tokens_details?: ResponseInputTokensDetails;
	output_tokens_details?: ResponseOutputTokensDetails;
}

export type ResponseInstructions = string | ResponseItem[];

export interface ResponseObject {
	id: string;
	object: "response";
	created_at: number;
	/** The status of the response generation. */
	status: ResponseStatus;
	/** The model used to generate the response. */
	model: string;
	/** The output items generated by the model. */
	output: ResponseItem[];
	/** The instructions used for the response. */
	instructions?: ResponseInstructions | null;
	/** Unix timestamp when this response completed. */
	completed_at?: number | null;
	/** The maximum number of output tokens. */
	max_output_tokens?: number | null;
	/** Maximum number of built-in tool calls processed for the response. */
	max_tool_calls?: number | null;
	/** SDK convenience text aggregated from output_text items. */
	output_text?: string;
	/** The temperature used for the response. */
	temperature?: number | null;
	/** The top_p used for the response. */
	top_p?: number | null;
	/** The tool_choice used for the response. */
	tool_choice?: ResponseToolChoice | null;
	/** The tools available to the model. */
	tools?: ResponseTool[];
	/** Whether parallel tool calls were enabled. */
	parallel_tool_calls?: boolean;
	/** The previous response ID for multi-turn. */
	previous_response_id?: string | null;
	/** Whether the response was stored. */
	store?: boolean;
	/** The streaming status. */
	stream?: boolean;
	/** The prompt template used. */
	prompt?: {
		id: string;
		version?: string;
		variables?: Record<string, string | ResponseInputContent>;
	} | null;
	/** The service tier used. */
	service_tier?: ServiceTier | null;
	/** The metadata attached. */
	metadata?: Metadata;
	/** Token usage statistics. */
	usage?: ResponseUsage | null;
	/** An error object. */
	error?: ResponseError | null;
	/** Details about why the response is incomplete. */
	incomplete_details?: ResponseIncompleteDetails | null;
	/** Context management configuration. */
	context_management?:
		| {
				type: string;
				compact_threshold?: number;
		  }[]
		| null;
	/** Conversation this response belongs to. */
	conversation?: { id: string } | null;
	/** The reasoning configuration. */
	reasoning?: {
		effort?: ReasoningEffort;
		generate_summary?: ReasoningSummary;
		summary?: ReasoningSummary;
	} | null;
	/** Summaries of the reasoning process. */
	reasoning_summaries?: SummaryTextContent[] | null;
	/** The text response configuration. */
	text?: {
		format?: ResponseFormatTextConfig;
		verbosity?: Verbosity;
	} | null;
	/** The truncation strategy. */
	truncation?: TruncationStrategy;
	/** The user identifier. */
	user?: string | null;
	/** The prompt cache key. */
	prompt_cache_key?: string | null;
	/** The prompt cache retention. */
	prompt_cache_retention?: PromptCacheRetention | null;
	/** The safety identifier. */
	safety_identifier?: string | null;
	/** Include parameter. */
	include?: ResponseIncludable[];
	/** Background mode. */
	background?: boolean;
}
