// src/providers/anthropic/messages-api.ts
//
// Decorator-based HTTP client for the Anthropic Messages API.
//
// Mirrors `src/providers/shared/chat-api.ts` but for POST /v1/messages
// with `x-api-key` + `anthropic-version` headers instead of Bearer auth.
// Kept as a separate file (rather than generalizing chat-api.ts) to stay
// strictly additive per Phase B risk policy: existing Chat providers stay
// untouched.

import {
	type BaseURLCapable,
	Fetcher,
	type TimeoutCapable,
} from "@ahoo-wang/fetcher";
import {
	type ApiMetadata,
	type ApiMetadataCapable,
	api,
	autoGeneratedError,
	body,
	post,
} from "@ahoo-wang/fetcher-decorator";
import type { JsonServerSentEventStream } from "@ahoo-wang/fetcher-eventstream";
import { JsonStreamResultExtractor } from "../shared/stream-result-extractor";
import type {
	AnthropicMessagesRequest,
	AnthropicMessagesResponse,
	AnthropicStreamEvent,
} from "./protocol";

export const ANTHROPIC_API_VERSION = "2023-06-01";

export interface MessagesApiOptions extends BaseURLCapable, TimeoutCapable {
	apiKey: string;
}

const MESSAGES_ENDPOINT = "v1/messages";

@api()
export class MessagesApi implements ApiMetadataCapable {
	constructor(public readonly apiMetadata?: ApiMetadata) {}

	@post(MESSAGES_ENDPOINT)
	messages(
		@body() request: AnthropicMessagesRequest,
	): Promise<AnthropicMessagesResponse> {
		throw autoGeneratedError(request);
	}

	@post(MESSAGES_ENDPOINT, {
		resultExtractor: JsonStreamResultExtractor,
	})
	streamMessages(
		@body() request: AnthropicMessagesRequest,
	): Promise<JsonServerSentEventStream<AnthropicStreamEvent>> {
		throw autoGeneratedError(request);
	}
}

export function messagesApi(options: MessagesApiOptions): MessagesApi {
	const fetcher = new Fetcher({
		baseURL: options.baseURL,
		timeout: options.timeout,
		headers: {
			"x-api-key": options.apiKey,
			"anthropic-version": ANTHROPIC_API_VERSION,
		},
	});
	return new MessagesApi({ fetcher: fetcher });
}
