import sys
src = chr(10).join([
  '// verify-godex-wire-shape.mjs',
  '// Run with: bun tools/verify-godex-wire-shape.mjs',
  '// 用 GodeX 真实的 normalizeCurrentInput 把 Responses input_image/video/audio',
  '// 转为 Chat Completions 消息，再补上 minimax hook 加的 reasoning_split / max_completion_tokens',
  '// 打印出来，跟探测脚本发的 payload 一字一字对。',
  '',
  'import { normalizeCurrentInput } from "../src/bridge/request/input-normalizer.ts";',
  '',
  'function show(label, req) {',
  '    const messages = normalizeCurrentInput(req, {',
  '        supportsImageInput: true,',
  '        supportsVideoInput: true,',
  '    });',
  '    const wire = {',
  '        model: req._model,',
  '        reasoning_split: true,',
  '        max_completion_tokens: req.max_output_tokens,',
  '        messages,',
  '    };',
  '    console.log("===", label, "===");',
  '    console.log(JSON.stringify(wire, null, 2).slice(0, 2000));',
  '    console.log("---");',
  '}',
  '',
  'const PNG_1X1 = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==";',
  'const MP4_URL = "https://example.com/test.mp4";',
  '',
  'show("image inline base64", {',
  '    _model: "MiniMax-M2.7",',
  '    max_output_tokens: 4096,',
  '    input: [{',
  '        role: "user",',
  '        content: [',
  '            { type: "input_text", text: "What color is the image?" },',
  '            { type: "input_image", image_url: PNG_1X1, detail: "low" }',
  '        ]',
  '    }]',
  '});',
  '',
  'show("video url", {',
  '    _model: "MiniMax-M3",',
  '    max_output_tokens: 4096,',
  '    input: [{',
  '        role: "user",',
  '        content: [',
  '            { type: "input_text", text: "Describe the video." },',
  '            { type: "input_file", file_url: MP4_URL }',
  '        ]',
  '    }]',
  '});',
  '',
  'show("function_call", {',
  '    _model: "MiniMax-M2.7",',
  '    max_output_tokens: 4096,',
  '    input: [{ role: "user", content: "Weather in Tokyo?" }],',
  '    tools: [{',
  '        type: "function",',
  '        name: "get_weather",',
  '        description: "Get current weather",',
  '        parameters: { type: "object", properties: { city: { type: "string" } }, required: ["city"] }',
  '    }],',
  '    tool_choice: "required"',
  '});',
])
open(r"D:/Documents/VibeCoding/GodeX/tools/verify-godex-wire-shape.mjs", "w", encoding="utf-8").write("\n".join(src))
print("wrote", sum(len(s) for s in src), "bytes")
