import {
	type BaseURLCapable,
	Fetcher,
	ResponseResultExtractor,
	type ResultExtractor,
	type TimeoutCapable,
} from "@ahoo-wang/fetcher";
import {
	type ApiMetadata,
	type ApiMetadataCapable,
	api,
	autoGeneratedError,
	body,
	get,
	post,
} from "@ahoo-wang/fetcher-decorator";
import type { JsonServerSentEventStream } from "@ahoo-wang/fetcher-eventstream";
import "@ahoo-wang/fetcher-eventstream";
import type {
	ResponseCreateRequest,
	ResponseObject,
	ResponseStreamEvent,
} from "../protocol/openai/responses";

export interface GodeXClientOptions extends BaseURLCapable, TimeoutCapable {
	apiKey: string;
}

export interface GodeXHealthResponse {
	status: "ok";
	timestamp: number;
}

export interface GodeXModelsResponse {
	object: "list";
	data: Array<{ id: string; object: "model"; owned_by: string }>;
}

export interface GodeXClient {
	readonly health: GodeXHealthApi;
	readonly models: GodeXModelsApi;
	readonly responses: GodeXResponsesApi;
}

const GodexStreamResultExtractor: ResultExtractor<
	JsonServerSentEventStream<ResponseStreamEvent>
> = (exchange) => {
	return exchange.requiredResponse.requiredJsonEventStream<ResponseStreamEvent>();
};

@api()
export class GodeXHealthApi implements ApiMetadataCapable {
	constructor(public readonly apiMetadata?: ApiMetadata) {}

	@get("health")
	get(): Promise<GodeXHealthResponse> {
		throw autoGeneratedError();
	}
}

@api()
export class GodeXModelsApi implements ApiMetadataCapable {
	constructor(public readonly apiMetadata?: ApiMetadata) {}

	@get("v1/models")
	list(): Promise<GodeXModelsResponse> {
		throw autoGeneratedError();
	}
}

@api()
export class GodeXResponsesApi implements ApiMetadataCapable {
	constructor(public readonly apiMetadata?: ApiMetadata) {}

	@post("v1/responses")
	create(@body() request: ResponseCreateRequest): Promise<ResponseObject> {
		throw autoGeneratedError(request);
	}

	@post("v1/responses", {
		resultExtractor: ResponseResultExtractor,
	})
	createRaw(@body() request: ResponseCreateRequest): Promise<Response> {
		throw autoGeneratedError(request);
	}

	@post("v1/responses", {
		resultExtractor: GodexStreamResultExtractor,
	})
	stream(
		@body() request: ResponseCreateRequest,
	): Promise<JsonServerSentEventStream<ResponseStreamEvent>> {
		throw autoGeneratedError(request);
	}
}

export function godexClient(options: GodeXClientOptions): GodeXClient {
	const fetcher = new Fetcher({
		baseURL: normalizeRootBaseURL(options.baseURL),
		timeout: options.timeout,
		validateStatus: () => true,
		headers: {
			Authorization: `Bearer ${options.apiKey}`,
		},
	});
	const apiMetadata = { fetcher };
	return {
		health: new GodeXHealthApi(apiMetadata),
		models: new GodeXModelsApi(apiMetadata),
		responses: new GodeXResponsesApi(apiMetadata),
	};
}

export async function collectGodexStreamEvents(
	stream: JsonServerSentEventStream<ResponseStreamEvent>,
): Promise<ResponseStreamEvent[]> {
	const reader = stream.getReader();
	const events: ResponseStreamEvent[] = [];
	try {
		while (true) {
			const { done, value } = await reader.read();
			if (done) return events;
			events.push(value.data);
		}
	} finally {
		reader.releaseLock();
	}
}

function normalizeRootBaseURL(baseURL: string): string {
	return baseURL.replace(/\/+$/, "").replace(/\/v1$/, "");
}
